---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-demo-microservices
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/zaibfridi/flux-demo-microservices
  secretRef:
    name: flux-demo-microservices
