---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/zaibfridi/flux-demo-production
  secretRef:
    name: flux-demo-production
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
